# Generated by Django 4.2.1 on 2023-10-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
